spring:
  application:
    name: seen-it

  datasource:
    url: jdbc:postgresql://localhost:5432/seenit
    username: postgres
    password: postgres1
    driver-class-name: org.postgresql.Driver


  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.jdbc.core: ERROR

app:
  service:
    base-url: http://www.omdbapi.com/
    api-key: ${OMDB_API_KEY}