spring:
  application:
    name: seen-it

  datasource:
    url: jdbc:postgresql://localhost:5432/media_tracker
    username: postgres
    password: postgres1
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.jdbc.core: DEBUG

app:
  service:
    base-url: http://www.omdbapi.com/
    api-key: REMOVED_OMDB_API_KEY # todo: base64 encrypt api key later